{
 "title": "Gotenberg Manager",
 "tags": [
  "gotenberg",
  "go"
 ],
 "panels": [
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method, status) (rate(http_requests_total[5m]))",
     "legendFormat": "{{method}} - HTTP {{status}}"
    }
   ]
  },
  {
   "title": "PDF Conversions (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(mode, status) (rate(pdf_conversions_total[5m]))",
     "legendFormat": "{{mode}} - HTTP {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Request Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95 Latency"
    }
   ]
  },
  {
   "title": "Total PDF Conversions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "sum(pdf_conversions_total)", "legendFormat": "Total" }
   ]
  }
 ]
}