apiVersion: v1
kind: ConfigMap
metadata:
  name: gotenberg-api-definition
  namespace: tyk
  labels:
    app: tyk-gateway
    tyk.io/api-id: "gotenberg-v1"
data:
  gotenberg-api.json: |
    {
      "name": "Gotenberg PDF API",
      "api_id": "gotenberg-v1",
      "org_id": "default",
      "use_keyless": false,
      "use_standard_auth": true,
      "active": true,
      "version_data": {
        "not_versioned": true,
        "versions": {
          "Default": {
            "name": "Default",
            "use_extended_paths": true
          }
        }
      },
      "proxy": {
        "listen_path": "/pdf/",
        "target_url": "http://gotenberg.gotenberg.svc.cluster.local:3000/",
        "strip_listen_path": true
      }
    }
